[tool.poetry]
name = "kane"
version = "0.1.0"
description = "シンプルな研修動画LMS（Learning Management System）"
authors = ["Takuya Kanesaki"]
packages = [{ include = "kane" }]

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
black = "^24.1.1"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
